

platform: x64

configuration: Release



   #nuget restore
  # '%APPVEYOR_BUILD_FOLDER%\lib\src\winbuild.bat'

  
  
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\dotnet"
  - nuget restore
  - cd "%APPVEYOR_BUILD_FOLDER%\lib\src"
  - winbuild.bat
  - dir "%APPVEYOR_BUILD_FOLDER%\lib"
  - dir "%APPVEYOR_BUILD_FOLDER%\lib\bin\release"
  
  
  
on_success:
  # Switch branches to gh-pages, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  #- rmdir /s/q docs
  #- xcopy temp\html docs\ /e
  - git config --global credential.helper store
  - git config --global user.email "cameron-elliott@users.noreply.github.com"
  - git config --global user.name "Cameron Elliott"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout master
  #- git remote set-url origin https://github.com/daveaglick/daveaglick.git
 # - git add -A
  - dir 
  - dir lib
  - git add -A lib\bin
  - git commit -a -m "Commit from AppVeyor [ci skip]"
  - git push
