

platform: x64

configuration: Release



   #nuget restore
  # '%APPVEYOR_BUILD_FOLDER%\lib\src\winbuild.bat'

  
  
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\dotnet"
  - nuget restore
  - cd "%APPVEYOR_BUILD_FOLDER%\lib\src"
  - winbuild.bat
