environment:
  access_token:
    secure: JzZz7EBJ8LeHp8E4NNoZi2DHm2roUthD4/6OAO6TrnUkdgK2v6UPFwWk2KEnOWdS

platform: x64

configuration: Release

init:
  - git config --global credential.helper store
  # visit http://cameronelliott.com to contact me. I want to hear from you.
  - git config --global user.email "cameron-elliott@users.noreply.github.com"
  - git config --global user.name "Cameron Elliott"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"

install:
  # Checkout master branch
  - git checkout master
  - cinst docfx

   #nuget restore
  # '%APPVEYOR_BUILD_FOLDER%\lib\src\winbuild.bat'

  
  
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\dotnet"
  #- nuget restore
  - cd "%APPVEYOR_BUILD_FOLDER%\lib\src"
 # - winbuild.bat
 #  - git checkout master
#  - git add -f -A  "%APPVEYOR_BUILD_FOLDER%\lib\bin"
#  - git commit -a -m "Commit from AppVeyor master"
  
  
  
on_success:
  # Switch branches to gh-pages, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  #- rmdir /s/q docs
  #- xcopy temp\html docs\ /e
    #  docfx build --logLevel Verbose docfx.json
  - cd "%APPVEYOR_BUILD_FOLDER%\docfx_project"
  - docfx "%APPVEYOR_BUILD_FOLDER%\docfx_project" -o "%APPVEYOR_BUILD_FOLDER%\..\docout"
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - git checkout gh-pages
  - git rm -rf .
  - xcopy "%APPVEYOR_BUILD_FOLDER%\..\docout" . /E
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  - git push
 


