### YamlMime:ManagedReference
items:
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration
  commentId: T:LimeVideoSDKQuickSync.TranscoderConfiguration
  id: TranscoderConfiguration
  parent: LimeVideoSDKQuickSync
  children:
  - LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream(System.IO.Stream,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.mfxIMPL,System.Boolean)
  - LimeVideoSDKQuickSync.TranscoderConfiguration.decParams
  - LimeVideoSDKQuickSync.TranscoderConfiguration.encParams
  - LimeVideoSDKQuickSync.TranscoderConfiguration.vppParams
  langs:
  - csharp
  - vb
  name: TranscoderConfiguration
  nameWithType: TranscoderConfiguration
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration
  type: Class
  source:
    remote:
      path: dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
      branch: master
      repo: https://github.com/cameron-elliott/LimeVideoSDK.git
    id: TranscoderConfiguration
    path: ../dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
    startLine: 13
  assemblies:
  - LimeVideoSDKQuickSync
  namespace: LimeVideoSDKQuickSync
  summary: "\nThis is used fully specify a transcoder configuration\n"
  example: []
  syntax:
    content: public class TranscoderConfiguration
    content.vb: Public Class TranscoderConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration.decParams
  commentId: F:LimeVideoSDKQuickSync.TranscoderConfiguration.decParams
  id: decParams
  parent: LimeVideoSDKQuickSync.TranscoderConfiguration
  langs:
  - csharp
  - vb
  name: decParams
  nameWithType: TranscoderConfiguration.decParams
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration.decParams
  type: Field
  source:
    remote:
      path: dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
      branch: master
      repo: https://github.com/cameron-elliott/LimeVideoSDK.git
    id: decParams
    path: ../dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
    startLine: 16
  assemblies:
  - LimeVideoSDKQuickSync
  namespace: LimeVideoSDKQuickSync
  summary: Decoder parameters
  example: []
  syntax:
    content: public mfxVideoParam decParams
    content.vb: Public decParams As mfxVideoParam
    return:
      type: LimeVideoSDKQuickSync.mfxVideoParam
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration.vppParams
  commentId: F:LimeVideoSDKQuickSync.TranscoderConfiguration.vppParams
  id: vppParams
  parent: LimeVideoSDKQuickSync.TranscoderConfiguration
  langs:
  - csharp
  - vb
  name: vppParams
  nameWithType: TranscoderConfiguration.vppParams
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration.vppParams
  type: Field
  source:
    remote:
      path: dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
      branch: master
      repo: https://github.com/cameron-elliott/LimeVideoSDK.git
    id: vppParams
    path: ../dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
    startLine: 18
  assemblies:
  - LimeVideoSDKQuickSync
  namespace: LimeVideoSDKQuickSync
  summary: The VPP parameters
  example: []
  syntax:
    content: public mfxVideoParam vppParams
    content.vb: Public vppParams As mfxVideoParam
    return:
      type: LimeVideoSDKQuickSync.mfxVideoParam
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration.encParams
  commentId: F:LimeVideoSDKQuickSync.TranscoderConfiguration.encParams
  id: encParams
  parent: LimeVideoSDKQuickSync.TranscoderConfiguration
  langs:
  - csharp
  - vb
  name: encParams
  nameWithType: TranscoderConfiguration.encParams
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration.encParams
  type: Field
  source:
    remote:
      path: dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
      branch: master
      repo: https://github.com/cameron-elliott/LimeVideoSDK.git
    id: encParams
    path: ../dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
    startLine: 20
  assemblies:
  - LimeVideoSDKQuickSync
  namespace: LimeVideoSDKQuickSync
  summary: The encoder parameters
  example: []
  syntax:
    content: public mfxVideoParam encParams
    content.vb: Public encParams As mfxVideoParam
    return:
      type: LimeVideoSDKQuickSync.mfxVideoParam
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream(System.IO.Stream,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.mfxIMPL,System.Boolean)
  commentId: M:LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream(System.IO.Stream,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.mfxIMPL,System.Boolean)
  id: BuildTranscoderConfigurationFromStream(System.IO.Stream,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.CodecId,LimeVideoSDKQuickSync.mfxIMPL,System.Boolean)
  parent: LimeVideoSDKQuickSync.TranscoderConfiguration
  langs:
  - csharp
  - vb
  name: BuildTranscoderConfigurationFromStream(Stream, CodecId, CodecId, mfxIMPL, Boolean)
  nameWithType: TranscoderConfiguration.BuildTranscoderConfigurationFromStream(Stream, CodecId, CodecId, mfxIMPL, Boolean)
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream(System.IO.Stream, LimeVideoSDKQuickSync.CodecId, LimeVideoSDKQuickSync.CodecId, LimeVideoSDKQuickSync.mfxIMPL, System.Boolean)
  type: Method
  source:
    remote:
      path: dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
      branch: master
      repo: https://github.com/cameron-elliott/LimeVideoSDK.git
    id: BuildTranscoderConfigurationFromStream
    path: ../dotnet/Class Libraries/LimeVideoSDKQuickSync/TranscoderConfiguration.cs
    startLine: 29
  assemblies:
  - LimeVideoSDKQuickSync
  namespace: LimeVideoSDKQuickSync
  summary: Builds the transcoder configuration from stream.
  example: []
  syntax:
    content: public static TranscoderConfiguration BuildTranscoderConfigurationFromStream(Stream inStream, CodecId inputCodecId, CodecId outputCodecId, mfxIMPL implementation = mfxIMPL.MFX_IMPL_AUTO, bool useOpaqueSurfaces = true)
    content.vb: Public Shared Function BuildTranscoderConfigurationFromStream(inStream As Stream, inputCodecId As CodecId, outputCodecId As CodecId, implementation As mfxIMPL = mfxIMPL.MFX_IMPL_AUTO, useOpaqueSurfaces As Boolean = True) As TranscoderConfiguration
    parameters:
    - id: inStream
      type: System.IO.Stream
      description: The in stream.
    - id: inputCodecId
      type: LimeVideoSDKQuickSync.CodecId
      description: The input codec identifier.
    - id: outputCodecId
      type: LimeVideoSDKQuickSync.CodecId
      description: The output codec identifier.
    - id: implementation
      type: LimeVideoSDKQuickSync.mfxIMPL
      description: The implementation.
    - id: useOpaqueSurfaces
      type: System.Boolean
      description: if set to <code>true</code> [use opaque surfaces].
    return:
      type: LimeVideoSDKQuickSync.TranscoderConfiguration
      description: ''
  overload: LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: LimeVideoSDKQuickSync
  commentId: N:LimeVideoSDKQuickSync
  isExternal: false
  name: LimeVideoSDKQuickSync
  nameWithType: LimeVideoSDKQuickSync
  fullName: LimeVideoSDKQuickSync
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: LimeVideoSDKQuickSync.mfxVideoParam
  commentId: T:LimeVideoSDKQuickSync.mfxVideoParam
  parent: LimeVideoSDKQuickSync
  isExternal: false
  name: mfxVideoParam
  nameWithType: mfxVideoParam
  fullName: LimeVideoSDKQuickSync.mfxVideoParam
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream*
  commentId: Overload:LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream
  isExternal: false
  name: BuildTranscoderConfigurationFromStream
  nameWithType: TranscoderConfiguration.BuildTranscoderConfigurationFromStream
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration.BuildTranscoderConfigurationFromStream
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: LimeVideoSDKQuickSync.CodecId
  commentId: T:LimeVideoSDKQuickSync.CodecId
  parent: LimeVideoSDKQuickSync
  isExternal: false
  name: CodecId
  nameWithType: CodecId
  fullName: LimeVideoSDKQuickSync.CodecId
- uid: LimeVideoSDKQuickSync.mfxIMPL
  commentId: T:LimeVideoSDKQuickSync.mfxIMPL
  parent: LimeVideoSDKQuickSync
  isExternal: false
  name: mfxIMPL
  nameWithType: mfxIMPL
  fullName: LimeVideoSDKQuickSync.mfxIMPL
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: LimeVideoSDKQuickSync.TranscoderConfiguration
  commentId: T:LimeVideoSDKQuickSync.TranscoderConfiguration
  parent: LimeVideoSDKQuickSync
  isExternal: false
  name: TranscoderConfiguration
  nameWithType: TranscoderConfiguration
  fullName: LimeVideoSDKQuickSync.TranscoderConfiguration
- uid: System.IO
  commentId: N:System.IO
  isExternal: false
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
